server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - LoggingGatewayFilterFactory
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AddHeader=custom-user-header,custom-user-header-value
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
          filters:
              - AddHeader=custom-car-header,custom-car-header-value
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**
          filters:
              - AddHeader=custom-bike-header,custom-bike-header-value
